### PR TITLE
Update Qt and Heroku Toolbelt recipes

### PR DESCRIPTION
**Pull request by mkostick**
- Remove unnecessary included recipe for Qt
- Allow Heroku Toolbelt plugins to be specified in the node configuration

### CODE REVIEW

**Comment by mike-yesware** [comment]
Is this starting to drift too far from upstream? Will we ever be able to merge in? (or do we not want to anymore?)

**Comment by mkostick** [comment]
Are you asking whether we ever want to submit a pull back to the original repo?  From the beginning, I thought this fork was made so we could make customizations (the first being removing bash_it) that explicitly deviate from the original.

**Comment by mkostick** [comment]
@mike-yesware @meghan-mcqueeney comments on this?

**Comment by meghan-mcqueeney** [comment]
This looks good to me.

**Pull request merged**
